### ISSUE TITLE
collection.js:279 Uncaught TypeError: this.elems is not a function

### ISSUE THREAD

**Issue by alex-embitel** [razorpay/razorpay-magento#110] opened 2018-04-10 12:58 UTC
After installing this module im getting "collection.js:279 Uncaught TypeError: this.elems is not a function" this error in "/en_US/Magento_Ui/js/lib/core/collection.js:279".

when I switching from checkout shipping method to payment method I'm getting this error.

check the below screenshot for the reference.
![screenshot from 2018-04-10 18 26 31](https://user-images.githubusercontent.com/36266281/38558094-bf21ba92-3cec-11e8-9d63-0a9163550512.png)

Please help me out from this issue.

Thank you !

**Comment by Mayur-Wadpalliwar** [comment] 2018-04-10 16:26
The issue is not due to the Razorpay files.

**Comment by alex-embitel** [comment] 2018-04-11 05:14
Okay, Thank you for the response.

But if I disable the Razorpay module, I'm not getting that error.

vendor/razorpay/magento/view/frontend/web/js/view/payment/method-renderer/razorpay-method.js
this js, initObservable function giving an error.

If I comment that function working fine, i couldn't make the order with Razorpay payment method.

**Comment by mukhund** [comment] 2018-05-14 13:07
Getting the same issue reported by @alex-embitel when Razorpay module is enabled:

collection.min.js:8 Uncaught TypeError: this.elems is not a function
    at UiClass._updateCollection (collection.min.js:8)
    at UiClass._insert (collection.min.js:8)
    at Registry._resolveRequest (registry.min.js:16)
    at Array.forEach (<anonymous>)
    at Registry._updateRequests (registry.min.js:16)
    at later (underscore.min.js:41)

Please acknowledge and provide solution.

![image](https://user-images.githubusercontent.com/25875568/39999125-d6b08e80-57a5-11e8-8282-21ac5a1caeb2.png)

**Comment by alvaialex** [comment] 2018-05-15 05:26
Hi Mukhund,

Try the below on "app/design/frontend/[Pakage]/[theme]/Magento_Razorpay/web/js/view/payment/method-renderer/razorpay-method.js"

Or 

directly you can edit the vendor razorpay js also 

           `initObservable: function() {
                var self = this._super();

                if(!self.razorpayDataFrameLoaded) {
                    $.getScript("https://checkout.razorpay.com/v1/checkout.js", function() {
                        self.razorpayDataFrameLoaded = true;
                    });
                }

                return self;
            },`

It got fixed for me.

**Comment by shubhambadkur12** [comment] 2018-05-15 06:15
@mukhund  what version of magento are you using ?

**Comment by mukhund** [comment] 2018-05-16 05:53
Thanks @alvaialex, your suggestion worked for me as well.

**Comment by nishantraut35** [comment] 2019-01-24 12:49
I have created pull request for this issue.
https://github.com/razorpay/razorpay-magento/pull/124

**Comment by namratavora** [comment] 2019-05-24 05:16
Thanks, @alvaialex, your suggestion worked for me too.

**Comment by harman28** [comment] 2019-06-26 05:35
Keeping this open till #124 is merged.

**Comment by harman28** [comment] 2019-07-01 06:42
Fix merged in #124

**Closed as completed by harman28** 2019-07-01 06:42 UTC
