### ISSUE TITLE
Error on checkout page. 

### ISSUE THREAD

**Issue by Aniket10Nov** [razorpay/razorpay-magento#119] opened 2018-09-05 10:05 UTC
Magento version 2.2.5.
On checkout page getting an error of Uncaught TypeError: this.elems is not a function on collection.js

Because of the error payment method is not change according to the selected billing address.

**Comment by jpeevi** [comment] 2018-09-06 10:25
Hello ,

Can you refer to this thread - https://github.com/razorpay/razorpay-magento/issues/110

**Comment by harman28** [comment] 2019-06-26 05:36
Closing as duplicate of #110

**Closed as completed by harman28** 2019-06-26 05:36 UTC
