### ISSUE TITLE
Razorpay plugin not working on Magento 2

### ISSUE THREAD

**Issue by sacsau** [razorpay/razorpay-magento#207] opened 2020-11-06 03:03 UTC
1. Razorpay logs error in console when payment button is clicked (see attached).
2. Razorpay payment goes through successfully.
3. Magento does not show success. Not does it place an order on the successful payment. Console shows yet another error "https://website/rest/website-name/V1/carts/mine/payment-information 500 (Internal Server Error)"

I had installed razorpay using composure. All configurations are done. I uninstalled and reinstalled again. Payments are happening but Razorpay pluging keeps the page spinning after successful payment and finally no order gets placed and 500 error is logged in console!

![razorpay-failed-magento](https://user-images.githubusercontent.com/69343128/98321401-fbba8980-200a-11eb-8527-5fccc8de4ded.png)

**Comment by ramth05** [comment] 2020-11-06 04:40
> 1. Razorpay logs error in console when payment button is clicked (see attached).
> 2. Razorpay payment goes through successfully.
> 3. Magento does not show success. Not does it place an order on the successful payment. Console shows yet another error "https://website/rest/website-name/V1/carts/mine/payment-information 500 (Internal Server Error)"
> 
> I had installed razorpay using composure. All configurations are done. I uninstalled and reinstalled again. Payments are happening but Razorpay pluging keeps the page spinning after successful payment and finally no order gets placed and 500 error is logged in console!
> 
> ![razorpay-failed-magento](https://user-images.githubusercontent.com/69343128/98321401-fbba8980-200a-11eb-8527-5fccc8de4ded.png)

@sacsau , Can you please provide your test site url and details of plugin version , magento version and system logs from `var/log/Razorpay` to this email `ramprakash.singh@razorpay.com` as well.

**Comment by giridhar1994** [comment] 2020-11-06 06:04
@sacsau can you also drop an email with all the above details to the support team for better assistance. [Link](https://razorpay.com/support/#)

**Comment by ramth05** [comment] 2020-11-09 04:23
The issue is with another module `DotDigital`, where it's unable to connect to SMTP server. The razorpay module working as expected. closing the issue.

**Closed as completed by ramth05** 2020-11-09 04:23 UTC
