### ISSUE TITLE
[Magento2] Razorpay payment method disappearing after applying discount

### ISSUE THREAD

**Issue by ccrims0n** [razorpay/razorpay-magento#54] opened 2017-05-25 05:58 UTC

**Comment by pmjcreations** [comment] 2017-05-25 06:05
Well, I am the victim here 😑

**Comment by webspeaks** [comment] 2017-05-28 08:05
It happens with me as well. Is there any solution?

**Comment by mayankamencherla** [comment] 2017-08-17 09:49
@webspeaks @pmjcreations Can you please share the exact version of your magento set up?

**Comment by pmjcreations** [comment] 2017-08-17 10:13
@mayankamencherla, are you still looking for the exact version of the Magento set up?
I see, your question is missing here.

**Comment by mayankamencherla** [comment] 2017-08-17 10:16
@pmjcreations Yes, please. Kindly share the exact version. Also if you can share the version of our plugin, and the error message / screen shot, it would be great.

**Comment by pmjcreations** [comment] 2017-08-17 10:21
When I created this issue, it was 2.1.5 or 2.1.6. I am not sure.
Currently, it is 2.1.8. Do you want me to run a test?

**Comment by pmjcreations** [comment] 2017-08-17 10:30
@mayankamencherla, you will get more information from Razorpay Integrations Reference number 62911
I haven't upgraded the plugin ever since I installed

**Comment by mayankamencherla** [comment] 2017-11-02 09:00
@pmjcreations Hi, Can you please share a screen shot of your browser console when you apply discount so that we can debug this further? You just post it here.

**Comment by pmjcreations** [comment] 2017-11-09 17:51
@mayankamencherla, I have reported a critical issue than this. Could you prioritise https://github.com/razorpay/razorpay-magento/issues/87?

**Comment by Jeeva-Rathinam** [comment] 2017-11-13 13:01
Is Razorpay good choice for Magento?

**Comment by mayankamencherla** [comment] 2017-12-07 14:34
@pmjcreations We have already fixed the issue #87, please confirm if everything is good.

**Comment by pmjcreations** [comment] 2017-12-07 17:36
@mayankamencherla this issue is no longer exist.
Current Magento version 2.2.1

Thank you

**Comment by mayankamencherla** [comment] 2017-12-11 12:20
@pmjcreations Does the coupon issue exist in magento 2.2? Because locally I am able to apply a coupon and make a payment. Could you please confirm this?

**Comment by pmjcreations** [comment] 2017-12-11 12:36
I made my comment above. The issue is no more. Confirmed with my current (and latest) Magento version 2.2.1

You may close this Issue, or if you need more information, I am available to help you.

**Comment by mayankamencherla** [comment] 2017-12-11 13:49
The issue is fixed in magento 2.2. Closing the issue.

**Closed by mayankamencherla** 2017-12-11 13:49 UTC
Labels: bug
